In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
vocab_size = 50
encoded_reviews = [one_hot(r, vocab_size) for r in reviews]
encoded_reviews

[[48, 17],
 [20, 28],
 [40, 26],
 [35, 46, 24],
 [11, 30, 28],
 [2, 17],
 [44, 30, 39],
 [20, 4],
 [20, 17],
 [30, 5]]

In [4]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
padded_reviews

array([[48, 17,  0],
       [20, 28,  0],
       [40, 26,  0],
       [35, 46, 24],
       [11, 30, 28],
       [ 2, 17,  0],
       [44, 30, 39],
       [20,  4,  0],
       [20, 17,  0],
       [30,  5,  0]])

In [5]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [6]:
X = padded_reviews
y = sentiment

In [7]:
model.compile(
    optimizer = 'adam', 
    loss = 'binary_crossentropy', 
    metrics = ['accuracy']
)

In [8]:
model.fit(X, y, epochs = 50, verbose = 0)

In [9]:
model.evaluate(X, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 1.0000 - loss: 0.6299


[0.6299372911453247, 1.0]

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [11]:
weights[21]

array([-0.04247853, -0.01643535, -0.03501449,  0.03702665], dtype=float32)

In [12]:
weights[45]

array([-0.01788728,  0.0493435 ,  0.01933462,  0.03462169], dtype=float32)

In [13]:
weights[4]

array([-0.05262876, -0.0223059 , -0.06261424, -0.08179744], dtype=float32)